### ISSUE TITLE
Connect with HRMP to Moonbeam on Moonbase 

### ISSUE THREAD

**Issue by haerdib** [integritee-network/parachain#107]
Open an HRMP channel with moonbeam on Rococo and register the TEER token on their chain.

https://docs.google.com/document/d/1W8y00IcJb0JXPBF59aP4nm-c7DY8Ld02-yIAO7UxR80/edit

- [ ] test token transfer on Rococo local with moonbeam (register asset and transfer with `xToken.transferWithFees`, see https://github.com/integritee-network/parachain/issues/98#issuecomment-1106583218)
- [x] open an HRMP channel manually on Rococo local
- [x] open an HRMP channel with Moonbeam on Rococo

**Comment by echevrier** [comment]
I managed to open an HRMP channel manually on Rococo local:

- [ ] Transfer enough balance to both sovereign accounts

- [ ] Ensure our parachain knows the rococo xcmp version

Request opening channels

- [ ] Integritee parachain request to open a HRMP channel to the moonriver parachain: : hrmp-> hrmpInitOpenChannel { recipient: 1000 (Moonriver ParaID), proposedMaxCapacity: 8, proposedMaxMessageSize: 1024} -> encoded call data : 0x1700e80300000800000000040000

- [ ] Moonriver parachain request to open a HRMP channel to the integritee parachain : hrmp-> hrmpInitOpenChannel { recipient: 2015 (Integritee ParaID), proposedMaxCapacity: 8, proposedMaxMessageSize: 1024} -> encoded call data : 0x1700df0700000800000000040000

Accept the opening requests 

- [ ] Moonriver parachain accept Integritee to Moonriver channel

•	hrmpAcceptOpenChannel with para id 2015 
•	hrmp -> hrmpAcceptOpenChannel{ sender: 2015 }
•	encoded call data 0x1701df070000 

- [ ] Integritee parachain accept Moonriver to Integritee channel

•	hrmpAcceptOpenChannel with para id 1000 
•	hrmp -> hrmpAcceptOpenChannel{ sender: 1000 }
•	encoded call data 0x1701e8030000

Open Integritee to Moonriver channel: 
- [ ] From integritee parachain send open request XCM Message (SUDO, integritee’s sovereign AccountId and open Integritee to Moonriver request encoded data call)  -> encoded data : 0x05002300010100021000040000000007005aca8b0913000000000700902f5009010700f2052a01060002286bee381700e803000008000000000400000d0100040001010070617261df070000000000000000000000000000000000000000000000000000
- [ ] On rococo got Event hrmp.OpenChannelRequest : { sender 2015, recipient 1000, proposed_max_capacity : 8, proposed_max_message_size: 1024}
- [ ] Accept request on moonriver: send accept XCM Message  (SUDO, moonriver’s sovereign AccountId and accept Integritee to Moonriver request encoded data call)  -> encoded data : 0x04001c00010100021000040000000007005aca8b0913000000000700902f500900060002286bee181701df0700000d0100040001010070617261e8030000000000000000000000000000000000000000000000000000
- [ ] On rococo got Event hrmp.OpenChannelAccepted : { sender 2015, recipient 1000}

Open Moonriver to Integritee channel
- [ ] From moonriverparachain send open request XCM Message (SUDO, moonriver’s sovereign AccountId and open Moonriver to Integritee request encoded data call)  -> encoded data : 0x04001c00010100021000040000000007005aca8b0913000000000700902f500900060002286bee381700df07000008000000000400000d0100040001010070617261e8030000000000000000000000000000000000000000000000000000
- [ ] On rococo got Event hrmp.OpenChannelRequest : { sender 1000, recipient 2015, proposed_max_capacity : 8, proposed_max_message_size: 1024}
- [ ] Accept request on Integritee : send accept XCM Message  (SUDO, Integritee ’s sovereign AccountId and accept Moonriver to Integritee request encoded data call)  -> encoded data : 0x05002300010100021000040000000007005aca8b0913000000000700902f5009010700f2052a01060002286bee181701e80300000d0100040001010070617261df070000000000000000000000000000000000000000000000000000
- [ ] On rococo got Event hrmp.OpenChannelAccepted : { sender 1000, recipient 2015}

**Comment by echevrier** [comment]
I try to register the TEER token on moonriver with registerForeignAsset. It seems to work but I'm unable to transfer any TEER: Erro:TooExpensive

**Comment by echevrier** [comment]
Integration with AlphanetEcosystem TestNet, according to https://docs.google.com/document/d/1W8y00IcJb0JXPBF59aP4nm-c7DY8Ld02-yIAO7UxR80/edit done:
- Integritee test parachain : https://polkadot.js.org/apps/?rpc=wss://moonbeam-test.integritee.network#/explorer
- Moonbase Alpha parachain : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbase.moonbeam.network#/explorer
- Moonbase Relay Chain : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffrag-moonbase-relay-rpc-ws.g.moonbase.moonbeam.network#/explorer

Integritee Parachain Sovereign Accounts:
- Sovereign Account Address on Relay: 0x70617261df070000000000000000000000000000000000000000000000000000
- Sovereign Account Address on other Parachains (Generic): 0x7369626cdf070000000000000000000000000000000000000000000000000000
- Sovereign Account Address on Moonbase Alpha: 0x7369626cdf070000000000000000000000000000

HRMP Channel
- Ensure Integritee parachain knows the moobase xcmp version :
encoded call data `0x05001f04010002000000`
- Integritee parachain propose to request to open a HRMP channel to the moonriver parachain :
    - Get the Relay Encoded Call Data to Open HRMP Channel
`hrmp-> hrmpInitOpenChannel { recipient: 1000 (Moonriver ParaID), proposedMaxCapacity: 8, proposedMaxMessageSize: 1024}`
encoded call data `0x3300640000000800000000040000`
    - Send XCM to Relay Chain 
   encoded call data `0x05002300010100021000040000000007005aca8b0913000000000700902f5009010700f2052a01060002286bee383300e803000008000000000400000d0100040001010070617261df070000000000000000000000000000000000000000000000000000`

- Accepting HRMP Channel with Moonbase Alpha
    - Get the Relay Encoded Call Data to Accept HRMP Channel : : `0x3301e8030000`
    - Send XCM to Relay Chain

- Asset details :
Multilocation of asset :` { "parents": 1, "interior": {"X2": [ { "Parachain": 2015 } {“GeneralKey” : TEER}] } }`
Asset Name:TEER
Asset symbol: TEER
Number of decimals 12

- Transfer TEER from Integritee to Moonbase Alpha 
Encoded call data `0x220101000102007d1f061054454552000700e876481701010200a10f030008480769599e23f626efff39b89f3137e9917a4000ca9a3b00000000`
-> Check events: https://polkadot.js.org/apps/?rpc=wss://moonbeam-test.integritee.network#/explorer/query/0x0389136c60700e4855fd373c7b6d41a43a5b6ac5b0b890db7d59dc8dd73fa3a4

- Transfer TEER from Moonbase Alpha to  Integritee
Encoded call data 
`0x1e0101000102007d1f061054454552000700205fa012010102007d1f0100c4db7bcb733e117c0b34ac96354b10d47e84a006b9e7e66a229d174e8ff2a06300ca9a3b00000000`
-> Check events: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbase.moonbeam.network#/explorer/query/0x57ba20ce65b659ff9f7a58a3dfa03c040e486fd032dd975f17998d9f769345d6
