### ISSUE TITLE
test runtime against v0.9.6 relaychain

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#11]
https://github.com/paritytech/polkadot/releases/tag/v0.9.6

**Comment by clangenb** [comment]
We postpone updating the collator?

**Comment by clangenb** [comment]
I could successfully register the parachain with the files contained in the zip from https://github.com/integritee-network/parachain/issues/4.

But I only checked if the `shell-kusama.state` produces blocks, I did not do extensive testing with other runtime configs.

Note 1: polkadot-launch needs to be updated to run with latest polkadot: https://github.com/paritytech/polkadot-launch/commit/152cbb5aea61630bc4232c7c6c7d66d667eb563d

Note 2: the error that polkadot-launch does nothing was simply because they renamed the binary: index.js -> cli.js

**Comment by clangenb** [comment]
Ah and I had to fix a tiny polkadot cli bug to be able to run polkadot-v0.9.6 with polkadot-launch:

https://github.com/encointer/polkadot/tree/fix-rococo-native-feature-flag

That branch is polkadot `release=v0.9.6` with a one liner fix.

**Comment by brenzi** [comment]
Here's a remark quote from Basti. Not sure if this is for us here (a bit dated already)
> @room There is a new branch polkadot-v0.9.4 that is compatible with the latest not yet released polkadot/kusama etc. Everyone that wants to launch on Kusama in the near future should upgrade to this. This is rather important. There was a bug (and still is in the trie) that leads to including the wasm runtime of the parachain in each proof. This commit works around this. For Kusama you should create a new genesis (don't forget to enable the GenesisConfig of ParachainSystem) and it will put the relevant data in the state to fix this bug. For everybody else needing to migrate, there are examples for an OnRuntimeUpgrade in Statemine/Westmine runtime. The other important commit is this that will switch to a better compressed proof format. This commit requires a staged upgrade of your parachain. Meaning first upgrade your runtime, then the old collators will not be able to produce any new blocks and then start the freshly build collators (these steps are only required for parachains that are already running and don't have this commit in their genesis).

**Comment by brenzi** [comment]
I guess we could upgrade the collator too. just wanted to know if it would work. Maybe worth asking in the channel what the best practise is for parachains that have not yet registered their wasm and state

**Comment by clangenb** [comment]
> 
> 
> Here's a remark quote from Basti. Not sure if this is for us here (a bit dated already)
> 
> > @room There is a new branch polkadot-v0.9.4 that is compatible with the latest not yet release...

Our collator already features this update.


Whether we should update depends on the schedule of our parathread/chain registration, I'd say. Such that we only need to update once, but have enough time to test it again.
