### ISSUE TITLE
Document happy flow of new upstream release

### ISSUE THREAD

**Issue by haerdib** [integritee-network/parachain#122]
+ version bump of parachain (spec + collator)
+ Parachain Changes: Check out diff in [cumulus repository](https://github.com/paritytech/cumulus)
+ Solochain update according to parachain changes or substrate diff: https://github.com/paritytech/substrate
+ Pallet claims: Is copied and pasted from https://github.com/paritytech/polkadot/blob/d5f16df743931d535441f28c605e619c16b971a3/runtime/common/src/claims.rs. If changes have been made, they can be directly taken from there
+ sgx-runtime sp-io: https://github.com/paritytech/substrate/tree/master/primitives/io (not copy pasted, but should contain the same functions)

**Comment by masapr** [comment]
I created a page in the wiki for this: https://integritee.atlassian.net/l/cp/hkoGX8gf

**Comment by masapr** [comment]
Documentation finished. @haerdib can you review?

**Comment by haerdib** [comment]
Reviewed, thanks for your work !
