### ISSUE TITLE
Obsolete `EnsureRoot`

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#138]
I can still find a few `EnsureRoot` in our runtime, shouldn't they all be removed know as we don't have a single root origin anymore?

@brenzi, @haerdib

**Comment by haerdib** [comment]
We don't have Sudo any more, but we still have a Root Origin, but it has to be voted for it accordingly. E.g. a passed referendum can instantiate a call with root origin.

**Comment by clangenb** [comment]
Ah yes. Sorry, I think you answered the same question before. :) It seems a bit counterintuitive to me. 

However, with this we deviate a bit from Polkadot's security design that the technical council is the only instance that can veto already accepted proposals, but I guess that is ok, we just need to remark that in our public docs.
