### ISSUE TITLE
open HRMP channel to Bifrost on Rococo

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#148]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbifrost-rpc.rococo.liebi.com%2Fws#/explorer

paraid 2001

**Comment by haerdib** [comment]
- [ ] Ensure the parachain account has sufficient balance (according to https://acala.discourse.group/t/open-hrmp-cross-chain-communication-between-kintsugi-and-karura-parachain/594 at least 10 KSM)
AccountId should be the same as our Kusama parachain: `5Ec4AhPXwiUhF3u21i56Uxc5XFUNEkKAq79kutWUAx1jyz47`
- [ ] Create an hrmp.hrmpInitOpenChannel request on rococo: `hrmp.hrmpInitOpenChannel(recipient: 2001, proposedMaxCapacity: 1000, proposedMaxMessageSize: 102400)`: ```0x1700d1070000e803000000900100``` 
- [ ] Create `hrmp.hrmpAcceptOpenChannel(2001)`: ```0x1701d1070000```
- [ ] Send with the sudo account the following: `0x05002300010100021000040000000007005aca8b0913000000000700902f5009010700f2052a01060002286bee381700d007000008000000000400000d0100040001010070617261ba0b0000000000000000000000000000000000000000000000000000`

- [ ] Accept the HRMP channel from Bifrost with the above created request: `0x05002300010100021000040000000007005aca8b0913000000000700902f5009010700f2052a01060002286bee181701d00700000d0100040001010070617261ba0b0000000000000000000000000000000000000000000000000000`

**Comment by haerdib** [comment]
Successfully opened a Channel Request to Bifrost on Rococo:

![grafik](https://user-images.githubusercontent.com/73821294/183357026-13df59d7-2926-4afa-91fa-580fba4f40c9.png)

@brenzi can you inform them?

**Comment by haerdib** [comment]
And the channels are open:
![grafik](https://user-images.githubusercontent.com/73821294/184073280-cebb1904-5944-4bdb-b018-38e311e97141.png)
![grafik](https://user-images.githubusercontent.com/73821294/184073292-2469d2c8-b476-4454-af6e-58db43330e8d.png)
