### ISSUE TITLE
move runtime constants to own module

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#15]
like Statemine: 
https://github.com/paritytech/cumulus/blob/11a0bca6d7e41a584250dd2166f66a2a9ec64365/polkadot-parachains/statemine-runtime/src/constants.rs

for both shell and integritee

also, check `deposit()` here:
https://github.com/paritytech/cumulus/blob/11a0bca6d7e41a584250dd2166f66a2a9ec64365/polkadot-parachains/statemine-runtime/src/constants.rs#L27

which is used for parametrized constants in the runtime

**Comment by clangenb** [comment]
Done: https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/common/src/lib.rs
