### ISSUE TITLE
bump to v0.9.27

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#150]
To fix: #149 

blocked by the orml deps, which are still on v0.9.27

**Comment by haerdib** [comment]
Not blocked anymore: orml now has a branch, still on draft, hopefully working though: https://github.com/open-web3-stack/open-runtime-module-library/tree/polkadot-v0.9.27

**Comment by haerdib** [comment]
While doing this task, also finish #122

**Comment by Niederb** [comment]
There is an other roadblock: The frontier repository can currently not be compiled with polkadot-v0.9.27. 
Also see this PR: https://github.com/paritytech/frontier/pull/809

**Comment by Niederb** [comment]
Update is done
