### ISSUE TITLE
Integritee Kusama Parachain syncing stuck at #38098/32819 with low # of peers

### ISSUE THREAD

**Issue by sourabhniyogi** [integritee-network/parachain#151]
We are trying to run an integritee full archive node (to get traces, xcm transfers indexed for https://integritee.polkaholic.io/chain/integritee#recentblocks) and found that after syncing the Kusama relay chain, our node is stuck at around #38098/32819 with a lack of peers (just 0,1,2 at most, none of which advance our parachain syncing)
```  
2022-08-03 00:12:57 💤 Idle (44 peers), best: #13837422 (0x2ae8…9e79), finalized #13837418 (0xdf46…329a), ⬇ 529.9kiB/s ⬆ 639.2kiB/s    
2022-08-03 00:12:59 💤 Idle (1 peers), best: #38219 (0x8484…e498), finalized #38098 (0x84ea…6f78), ⬇ 2.3kiB/s ⬆ 3.0kiB/s    
2022-08-03 00:13:00 ✨ Imported #13837423 (0xf8af…109c)    
2022-08-03 00:13:02 💤 Idle (44 peers), best: #13837423 (0xf8af…109c), finalized #13837418 (0xdf46…329a), ⬇ 92.0kiB/s ⬆ 262.4kiB/s    
2022-08-03 00:13:04 ⚙️  Syncing  0.0 bps, target=#706253 (2 peers), best: #38219 (0x8484…e498), finalized #38098 (0x84ea…6f78), ⬇ 2.3kiB/s ⬆ 2.7kiB/s    
2022-08-03 00:13:06 ✨ Imported #13837424 (0x81ca…73a4)    
```
Do you have a solution to get our node unstuck by finding more peers that are at the tip?

Our invocation is 
```
./target/release/integritee-collator --name integritee --base-path /root/.local/share/intregritee/ --chain /integritee/integritee-node/node/res/integritee-kusama.json --state-cache-size 1 --db-cache 2048 --runtime-cache-size 32 --rpc-methods Unsafe --unsafe-rpc-external --rpc-port 9100 --rpc-external --ws-external --ws-port 9944 --rpc-max-request-size 64 --unsafe-ws-external --pruning archive --no-prometheus --rpc-cors all
```
using the 1.5.28 binary in releases where the spec is 
https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/chain-specs/integritee-kusama.json

```
# head /integritee/integritee-node/node/res/integritee-kusama.json
{
  "bootNodes": [
    "/ip4/206.189.59.95/tcp/30333/p2p/12D3KooW9yxCm9MoTTtmH1cEQHwnTKhv3bCoiFwbRhRJU7sae4Yd",
    "/ip4/167.172.167.196/tcp/30333/p2p/12D3KooWBR4UmiGadvQ77m6iwWuoEUwgRkFMMhzhecXn2Hc9QUhC"
  ],
  "chainType": "Live",
  "codeSubstitutes": {},
  "consensusEngine": null,
  "forkId": null,
  "genesis": {
```

Can you please advise?  Thank you!

**Comment by clangenb** [comment]
I apologize for coming back to you so late. Yes, unfortunately this is a known issue. We describe the issue and the fix for it here: https://integritee-network.gitbook.io/integritee-wiki/readme-1/integritee-network/parachain-on-kusama#troubleshooting

This link is not yet indexed, but will be soon after a final of the documentation.

**Comment by clangenb** [comment]
Now we have the link to the official source: https://docs.integritee.network/5-nodes-and-infrastructure/5.1-how-to-set-up-and-run-integritee-network-nodes/5.1.1-full-node/5.1.1.1-parachain-on-kusama#troubleshooting
