### ISSUE TITLE
Open HRMP channel to Bifrost on Kusama

### ISSUE THREAD

**Issue by haerdib** [integritee-network/parachain#152]
- [x] Ensure the parachain account has sufficient balance (atleast 10 KSM). AccountId: `5Ec4AhPXwiUhF3u21i56Uxc5XFUNEkKAq79kutWUAx1jyz47`. Currently owns 20 KSM
❗  Update 11.10.2022: Currently owns 0.9 KSM, not enough for an HRMP channel.

- [x] Create a batch call on Kusama: ```0x1802083c01d10700003c00d1070000e803000000900100```
- [x] Create the XCM message on Integritee parachain: `0x230001010002140004000000000b00204aa9d10113000000000b00204aa9d101000600070050d6dc015c1802083c01d10700003c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
With preimage Hash: `0xd097b5ee4d6d31518b9eb9124bbc8c4598fbda85ea860fa17d28fadde7fa4ac3`
- [x] Submit the preimage on the Integritee Parachain: `0x0e0ea901230001010002140004000000000b00204aa9d10113000000000b00204aa9d101000600070050d6dc015c1802083c01d10700003c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
- [x] Propose an External motion with the preimage hash `0xd097b5ee4d6d31518b9eb9124bbc8c4598fbda85ea860fa17d28fadde7fa4ac3` (and vote for it accordingly)

### This did not work:  Too low fund and weights limit!
As Bifrost already sent an HRMP request, we can batch the Accept and Request call:
- [x] Create an hrmp.hrmpInitOpenChannel request on Kusama: `hrmp.hrmpInitOpenChannel(recipient: 2001, proposedMaxCapacity: 1000, proposedMaxMessageSize: 102400)`: ```0x3c00d1070000e803000000900100``` 
- [x] Create `hrmp.hrmpAcceptOpenChannel(2001)` request on Kusama: ```0x3c01d1070000```
- [x] Create a batch call on Kusama: ```0x1802083c01d10700003c00d1070000e803000000900100```
- [x] Create the XCM message on Integritee parachain: `0x230001010002140004000000000700e876481713000000000700e876481700060003009435775c1802083c01d10700003c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
With preimage Hash: `0xce1cb3bf6386b77934fa1197de6172ee0fefc30438f353c1e02476cce10c3433`
- [x] Submit the preimage on the Integritee Parachain: `0x0e0e9d01230001010002140004000000000700e876481713000000000700e876481700060003009435775c1802083c01d10700003c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
- [x] Propose a Motion with the preimage hash `0xce1cb3bf6386b77934fa1197de6172ee0fefc30438f353c1e02476cce10c3433` (and vote for it accordingly)

### OUTDATED (better to batch our calls)
Send an `OpenChannel` request with root privileges (Democracy):
- [x] Create an hrmp.hrmpInitOpenChannel request on Kusama: `hrmp.hrmpInitOpenChannel(recipient: 2001, proposedMaxCapacity: 1000, proposedMaxMessageSize: 102400)`: ```0x3c00d1070000e803000000900100``` 
- [x] Create an XCM `OpenChannel` request on the Integritee parachain:
`0x230001010002140004000000000700e876481713000000000700e87648170006000300943577383c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
With preimage Hash: `0x01e53f45353e541d5533d9774248ccf57f6d548b9162c9d2490cf5b3d6497a95`
- [x] Submit Preimage Extrinsic: `0x0e0e7901230001010002140004000000000700e876481713000000000700e87648170006000300943577383c00d1070000e803000000900100140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
- [x] Propose and vote on a Motion with the preimage hash of the `OpenChannel` request 

Accept the HRMP channel from Bifrost via root privileges (Democracy): 
- [x] Create `hrmp.hrmpAcceptOpenChannel(2001)` request on Kusama: ```0x3c01d1070000```
- [x] create an XCM `AcceptChannel` request on the Integritee parachain: `0x230001010002140004000000000700e876481713000000000700e87648170006000300943577183c01d1070000140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
With preimage Hash: `0xf376baa57997cd1d5a50408d48c9842e901d37b1274d183d6bd03f7cce9cb01b`
- [x] Submit Preimage Extrinsic: `0x0e0e5901230001010002140004000000000700e876481713000000000700e87648170006000300943577183c01d1070000140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
- [x] Propose and vote on a Motion with the preimage hash of the `AcceptChannel` request

**Comment by haerdib** [comment]
Tested the following on Rococo Local (polkadot v0.9.29):
❗  Rococo local has a max channel capacity of  8 and max message size of 1024. Unilke Rococo or Kusama.

- [x] Fund both parachains with Tokens
- [x] Ensure both parachains know the xcm version `polkadotXcm.forceXcmVersion` to 2

Create an open Channel request from Karura:
- [x] Create an hrmp.hrmpInitOpenChannel request on Rococo Local: `hrmp.hrmpInitOpenChannel(recipient: 2015, proposedMaxCapacity: 1000, proposedMaxMessageSize: 102400)`: ```0x1700df070000e803000000900100``` 
- [x] Ceate the xcm call (with values according to https://docs.substrate.io/reference/how-to-guides/parachains/add-hrmp-channels/) 
`0xff0038000101000214000400000000070010a5d4e81300000000070010a5d4e80006000300286bee381700df070000e803000000900100140d0100040001010070617261d0070000000000000000000000000000000000000000000000000000`
and send as sudo.

For the integritee parachain:
- [x] Create a Batch call on Rococo: `0x5a02081701d00700001700d00700000800000000040000`
- [x] Create xm call: `0x230001010002140004000000000b00204aa9d10113000000000b00204aa9d101000600070050d6dc015c5a02081701d00700001700d00700000800000000040000140d0100040001010070617261df070000000000000000000000000000000000000000000000000000`
With hash: `0x2ece4165578fea11d34933f7aec88337df7310472eb45f9a9ffe52777cd54b83`
-[x] submit preimage xt: `0x0e0ea901230001010002140004000000000b00204aa9d10113000000000b00204aa9d101000600070050d6dc015c5a02081701d00700001700d00700000800000000040000140d0100040001010070617261df070000000000000000000000000000000000000000000000000000` 
- [x] propose external with hash `0x2ece4165578fea11d34933f7aec88337df7310472eb45f9a9ffe52777cd54b83`
- [x] Check on rococo local: Executed:

![grafik](https://user-images.githubusercontent.com/73821294/196678920-0a0a5e25-b576-4cda-a9e7-5f90808edeaf.png)



Learnings: It works. Just need to increase amount withdrawn and max asset for Kusama call.

**Comment by clangenb** [comment]
This has been completed, see: https://integritee.subscan.io/xcm_dashboard

**Comment by clangenb** [comment]
This has been completed, see: https://integritee.subscan.io/xcm_dashboard
