### ISSUE TITLE
register parathread on Kusama for slot renewal

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#155]
Using [v1.5.31](https://github.com/integritee-network/parachain/releases/tag/1.5.31) with polkadot-v0.9.27

* [ ] think through the slot handover process and what needs to be there in the shell. can be done at later stage, but worth thinking about before
* [x] test most recent shell (with polkadot launch setup)
* [x] register wasm and state on Kusama
   * [x]  Wasm compact from from 1.5.31 release https://github.com/integritee-network/parachain/releases/download/1.5.31/shell_runtime-v4.compact.compressed.wasm
   * [x] State from 1.5.31: https://github.com/integritee-network/parachain/suites/8157955604/artifacts/354233071
Downloaded artifact: [shell-kusama-lease2-026861cbc4d7061381ec0612ef7c9d059c8e4a6b.zip](https://github.com/integritee-network/parachain/files/9500421/shell-kusama-lease2-026861cbc4d7061381ec0612ef7c9d059c8e4a6b.zip)
* [x] using new sudo key `2JcYbKMfEGidntYP1LpPWsCMxFvUbjaPyipRViat4Sn5nuqm`, see: https://github.com/integritee-network/parachain/pull/160

**Comment by clangenb** [comment]
Extracted slot handover process to #162
