### ISSUE TITLE
upgrade Kusama parachain to most recent runtime

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#156]
* [x] release parachain
* [x] test runtime on rococo with teeracle
* [x] initiate governance process on Kusama

**Comment by echevrier** [comment]
- Release [1.5.30](https://github.com/integritee-network/parachain/releases/tag/untagged-bb1ae7c0db20dc55d162)

**Comment by echevrier** [comment]
Local tested : runtime upgrade on local rococo network. 
- launch network 
  - parachain with integritee-collator : 1.5.27
  - relay chain with polkadot-v0.9.22

**Comment by echevrier** [comment]
Tested on rococo:
- runtime upgrade to 26
- build a production teeracle from https://github.com/integritee-network/worker/commit/d8b6b931a33526b27bba18f4bd4f789d8c8c170c
- run on devsgx03

Works:
![rococo_1](https://user-images.githubusercontent.com/84318241/188927189-ae06ab53-23e5-44de-b438-b2f096cf50a4.PNG)
