### ISSUE TITLE
Test if xcm still works on rococo after polkadot-v0.9.39 update

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#208]
The polkadot-v0.9.39 contained some XCM changes, see https://github.com/integritee-network/parachain/pull/205. We have to test if the open xcm channels are still functional.

**Comment by clangenb** [comment]
Just test if we can send some tokens over to bifrost or whoever

**Comment by brenzi** [comment]
Here the log of a previous test: https://github.com/integritee-network/parachain/issues/107#issuecomment-1135498850
unfortunately, can't decoded the call anymore

**Comment by brenzi** [comment]
Here's a recent  XCM transfer on kusama which succeeded:
https://integritee.subscan.io/extrinsic/2805037-2

encoded:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.integritee.network#/extrinsics/decode/0x22000000a0724e180900000000000000000000010102009d1f0300ef46c7649270c912704fb09b75097f6e32208b850102286bee

**Comment by brenzi** [comment]
here's a successful XCM form integritee(kusama) to Karura:
https://integritee.subscan.io/extrinsic/1107890-2
trying to replicate this one on rococo

**Comment by brenzi** [comment]
we just have no usable setup on rococo to test. Neither Karura nor Moonriver are on rococo, Bifrost is, but hasn't upgraded to a V3 release yet. and our xcm config isn't right anyway.
It seems like we need to test this on mainnet and act if we encounter errors
