### ISSUE TITLE
can't receive root calls over XCM

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#218]
On Rococo, it wasn't possible to rescue our parachain :+1: funds seem to be missing somewhere to execute XCM

attempts by Alejandro
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xdc7fcc8094465ceac6b0f75f7cfbba13072828a1cd1b3e5f5f1fff658970aa43

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x92e6e5d08d462548c73d99b4b3be3153d7368f35ac2b7457d145b4e7cf15a4ad

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x8fe042e4a605bb650af946e6f3f90ce8bb0d33549a353dd4d70b8058020723e3

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xff65e5359106bbf9f4a3f42f78e6989df526bd4bd8c041cf837367869c0f64d4

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x245eab695eb683969b8b8de89a2d992bc8f8616c3a95442f5850f048d8cb9750

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x99f2a547809586741d977623d303ee8db698cc7b8547d814c1e00e8de6b6c03e

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xe57bc728701804025d4ead9207ebb9f27e62567b27e06d7fc1cb455df8f6ef22

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xa8e6ff42f09657cc915ae46c64a0358cec2127040f48a134dfdc7d148673637e
* error: Barrier

**Comment by al3mart** [comment]
The source of the error is that the account corresponding to Parent doesn't have funds in IntegriTEE.
Source if the spam is me thinking I was sending a message to Encointer.

**Comment by clangenb** [comment]
I guess this is obsolete now, we have majorly changed the xcm config.
