### ISSUE TITLE
change (spec-)versioning scheme

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#226]
We currently have the problem that we can't perform the slot swap because of a runtime misconfig: https://github.com/integritee-network/parachain/issues/225. However, the master branch is already far ahead, and we don't want to perform the big runtime upgrade just because of that, as this is a bit risky because of considerable xcm changes. Hence, I propose to do a similar spec versioning as parity does: `1340`, which maps to major=1, minor=34, patch=0, where we usually don't increment the patch version. If we do it like this, we could for do a new patch release on a separate branch now, incrementing the runtime-spec patch version, without interfering with the already released minor versions on master branch.

**Comment by brenzi** [comment]
As we have no concept of major.minor for runtimes, I suggest the scheme `MMP`
Introduced this in 1.10.0 with spec_version 520 (instead of 52)
this allos for 9 patches which should be fine.
