### ISSUE TITLE
Localnet parchain blocks are not producing

### ISSUE THREAD

**Issue by shanithkk** [integritee-network/parachain#251]
## Description:
While i'm testing the chain manually using docker image, parachain is not producing blocks, showing like starting collation.

### Steps to reproduce
- Running two relay chains nodes
- Register para id (2000)
- create chain spec with chain id integritee-rococo-local-dev
- Edit the chain spec of parachain with 2000
- Build raw chain spec
- Running the parachain with created raw spec

## Expected outcome
Parachain should produce blocks

### Screenhot
![MicrosoftTeams-image (14)](https://github.com/integritee-network/parachain/assets/59169878/f32d8945-e375-49e4-9b47-a0689913eec3)

**Comment by brenzi** [comment]
may I ask you to provide the exact commands you use?
If you want to test a local parachain setup, consider using zombienet:
`zombienet-linux-x64 spawn --provider native zombienet/rococo-local-with-integritee.toml`

**Comment by shanithkk** [comment]
Im using docker image to run the node. 
```/usr/local/bin/integritee-collator --base-path=/tmp/integritee --chain=/build/integritee-raw.json --rpc-port=9947 --port=30333 --rpc-external --rpc-cors=all --prometheus-external --alice --collator --rpc-methods=unsafe --force-authoring --execution=wasm -- --chain=/app/raw-polkadot.json --execution=wasm ```.

I'm building a tool similar to zombinet to spawn nodes you can see [here](https://github.com/HugoByte/polkadot-kurtosis-package).

Raw file i'm attaching below
[integritee-raw.json](https://github.com/integritee-network/parachain/files/14110452/integritee-raw.json)

**Comment by brenzi** [comment]
suspicion: depending on how you built the spec you have to use the paraid we hardcoded for that spec. not 2000

https://github.com/integritee-network/parachain/blob/792f5910ebd94c083326fd41e8452f8ce932c4e6/polkadot-parachains/src/command.rs#L45-L51
