### ISSUE TITLE
OnFinality Setup

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#28]
BLOCKED BY: #29 

I am currently looking into a setup with OnFinality. A Setup is spun up via docker images, so we need to prepare one.

This is probably a good starting point to create the image: https://github.com/paritytech/substrate/blob/master/.maintain/Dockerfile.

Note: They add the binary as `CMD` at the end. OnFinality support said that it's better to use `EntryPoint`

Afterwards, we add a custom network according to:  https://support.onfinality.io/hc/en-us/articles/900001047926-Add-a-New-Custom-Network.

**Comment by clangenb** [comment]
We can publish to docker with GitHub actions directly. I am uncertain if this makes sense: [medium](https://medium.com/platformer-blog/lets-publish-a-docker-image-to-docker-hub-using-a-github-action-f0b17e5cceb3)

And we can run a GA workflow on tag creation only: https://github.com/actions/runner/issues/1007

**Comment by mosonyi** [comment]
Onfinality has fixed the security rules out-of-range issue on their side. All is up and working well.
