### ISSUE TITLE
slot lease swap on coretime polkadot

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#302]
guide:
https://hackmd.io/Z_XaRqWrRN-CgByGuqtvHQ

* [x] send >=5 DOT to sovereign account of 2039 on relaychain `subalfred key --type parachain 2039` => `5Ec4AhPckdo3hvAPioYZ7MwmrRNMhQi7CATU4STxMzq1RSrA`
* [x] check balance of Manager of 3359. ok
* [x] if XCM initialization is needed, do `forceXcmVersion(3)`: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fintegritee-rpc.dwellir.com#/extrinsics/decode/0x11001f04010003000000
* [x] on parachain 2039, sudo multisig calls https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.integritee.network#/extrinsics/decode/0x11001f0003010003140004000000000700e40b5402130000000007001a7118020006000700f2052a0182380100284603f70700001f0d0000140d0100000100dd1f
   * one block for approveAsMulti
   * one block to execute approval
* [x] para manager for 3359 calls the swap: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fpolkadot#/extrinsics/decode/0x46031f0d0000f7070000
* [x] observe Event registrar.swapped on relaychain
* **WAIT for the next core sale cycle on coretime para until blocks will be produced**

buy coretime onDemand for each extrinsic sequentially. minimum bet (0.025 DOT): https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fpolkadot#/extrinsics/decode/0x400180b2e60e000000000000000000000000f7070000
## details

ParaId 2039 (integritee-polkadot) is locked and has no lease
```
registrar.paras: Option<PolkadotRuntimeCommonParasRegistrarParaInfo>
{
  manager: 14xQXJdUDC1pzyt8y3z27ANiUBgP7zTSaYutaLELJoyQrdLP
  deposit: 5,102,100,000,000
  locked: true
}
```

ParaId 3359 (winning integritee auction bid) is unlocked and has a lease and should give it to 2039
```
registrar.paras: Option<PolkadotRuntimeCommonParasRegistrarParaInfo>
{
  manager: 14xQXJdUDC1pzyt8y3z27ANiUBgP7zTSaYutaLELJoyQrdLP
  deposit: 7,265,480,000,000
  locked: null
}
``` 

the para 2039 wants to execute this on the relaychain via XCM:
* call: `0x4603f70700001f0d0000`
* parachain sudo call: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.integritee.network#/extrinsics/decode/0x11001f0003010003140004000000000700e40b5402130000000007001a7118020006000700f2052a0182380100284603f70700001f0d0000140d0100000100dd1f

**Comment by bkontur** [comment]
@brenzi @SBalaguer
I think something like this should work for [failed](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fintegritee-rpc.dwellir.com#/explorer/query/0xf29a55d838be92a2a98c899ffb5326f585037ab8f2af5304448f2ea9045268c3):
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot.api.integritee.network#/extrinsics/decode/0x11000904081f040100030000001f0003000003140004000000000700e40b5402130000000007001a7118020006000700f2052a0182380100284603f70700001f0d0000140d0100000100dd1f

maybe it could be possible to test it with chopsticks

**Comment by SBalaguer** [comment]
Thanks @bkontur for reviewing it!

@brenzi this instruction adds as well setting the right supported version of XCM on the relay chain so that the second instruction can be executed.
