### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#32]
- [x] use cargo cache in cargo clippy also (the cache-key needs to be different from the cache key of the `build` stage.)
- [x] since using the cache, this compiler bug may occur: https://github.com/rust-lang/rust/issues/84970. We can fix the issue by running `cargo clean -p integritee-collator` before running cargo build.

**Comment by clangenb** [comment]
Added cache to cargo clippy, but GA does not execute this step somehow...

**Comment by brenzi** [comment]
done by @mosonyi, right? please close if yes

**Comment by clangenb** [comment]
Cache-key is solved. But the unstable fingerprint issue was not tackled.

**Comment by mosonyi** [comment]
Let me work on this a bit please

**Comment by mosonyi** [comment]
According to the related issue, it occurs rarely. Without cache the build takes ages. We'll use this workaround in case of any error in the future. @clangenb if you agree, please close or comment

**Comment by clangenb** [comment]
I have had it occur in CI already, and the problem is that you can't recover from it, so you can't just rerun the action. I suggest adding `cargo clean -p integritee-collator`  because it does not incur runtime overhead.
