### ISSUE TITLE
Test that registered parachain works with v0.9.8

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#35]
We have upgraded the parachain to polkadot-v0.9.8, and tested it. However, it would be great if we don't need to replaced our registration at kusama.

**Comment by clangenb** [comment]
@brenzi did you use these files for registration? https://gist.github.com/brenzi/9e45a60067342d8604899b241f789091

**Comment by clangenb** [comment]
Test with the artifacts used in  https://gist.github.com/brenzi/9e45a60067342d8604899b241f789091.

* Successfully produced blocks after key injection.

Could not test anything else with these binaries, as I don't have the sudo key. I will test some more with a wasm that is equally old and I have the root key.

**Comment by brenzi** [comment]
yes, used those files. so we're good to go
