### ISSUE TITLE
[CD] add collator binary and runtime wasm artifacts to releases

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#37]
When we release a new version of the parachain, GH actions should attach the following artifacts to the release:

* collator binary (Build workflow > integritee-collator-...... )
* runtime wasm (SRtool Build workflow > integritee-runtime)

**Comment by brenzi** [comment]
what do I need to check?

**Comment by mosonyi** [comment]
If the name of files and their content is good.

**Comment by brenzi** [comment]
In the release, the file is called `integritee-collator` and it is not compressed, so it's directly the binary. I think this is fine.
We'll need the runtime files too: shell-runtime, integritee-runtime

Polkadot also releases the binary `polkadot`without version or commit hash. But they add the runtime spec version to the filename of the runtime wasm. I think this makes a lot of sense. Can we easily extract that?

**Comment by brenzi** [comment]
can we close this?

**Comment by mosonyi** [comment]
Yes, it's done.
