### ISSUE TITLE
seedling-based migration from solochain to parachain setup

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#62]
https://hackmd.io/gNAwlyoXTK6L_veMGG4sSQ

https://github.com/paritytech/cumulus/tree/master/polkadot-parachains/seedling

Caveat!!

We have a pallet index collision to resolve between node (grandpa)  and shell parachain (aura-ext):
https://github.com/integritee-network/parachain/blob/747f4aca48afa516f4ca4786edfa7f8dfd190322/polkadot-parachains/shell-runtime/src/lib.rs#L364
https://github.com/integritee-network/integritee-node/blob/d9454f9f8f397a43bba2d4431f852e829d62004c/runtime/src/lib.rs#L595

**Comment by haerdib** [comment]
As far as I understood, the pallet clash should not matter during this process.

We need to do the following steps (order matters):
- [ ] Upgrade parachain node runtime to seedling runtime (which does not contain any pallet clashes)
    - State pruning?
    - pass key from solo-chain  (https://github.com/paritytech/substrate/blob/master/frame/sudo/src/lib.rs#L193 ?)
- [ ] Upgrade solo-chain runtime to parachain code
- [ ] Update seedling runtime to new parachain runtime by passing solo-chain header & runtime code to seedling parachain: https://github.com/paritytech/cumulus/blob/60b680ace0389d71d927acfb9ae1319b2c07c07d/pallets/solo-to-para/src/lib.rs#L73-L82
    - State transition?

**Comment by brenzi** [comment]
parity has paused seedling development because they hit blockers in substrate's architecture
