### ISSUE TITLE
OOM kill in kubernetes setup

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#70]
With the latest release [1.4.12](https://github.com/integritee-network/parachain/releases/tag/1.4.12) based on polkadot-v0.9.16, we get almost immediate OOM errors in the Kubernetes setup.

This was not the case before with polkadot-v0.9.13, and does not seem to be the case with encointer's latest release (polkadot-v.9.16).

We first thought that it has to do with the continuously increasing RAM usage of the node (3GiB after ~15minutes). However, encointer displays the same behavior and does not exhibit the OOM kill in its Kubernetes setup.

We currently have no idea about the reason behind this. We verified:

* verified that the same substrate, cumulus, polkadot dependency git hashes
* That the diff of the node(host) between encointer and integritee consists only of naming except for the chainspec-relevant stuff.

Command run:

```
./target/release/integritee-collator --name integritee-westend-new-local --chain 'shell-westend' --pruning archive --ws-max-connections '1000' --rpc-cors 'all' --ws-port=9945 --rpc-port=9934 --rpc-methods=Unsafe --unsafe-rpc-external --ws-external --execution=wasm --telemetry-url 'wss://shard.telemetry.integritee.io/submit\ 0' --prometheus-external -- --chain=westend --unsafe-pruning --pruning=1000 --execution=wasm --prometheus-external
```

[integritee-westend-oomkilled.log](https://github.com/integritee-network/parachain/files/8048619/integritee-westend-oomkilled.log)

**Comment by clangenb** [comment]
@mosonyi I think this is no longer relevant, is it?

**Comment by mosonyi** [comment]
Yepp, can be closed
