### ISSUE TITLE
substrate_proposer_block_constructed_count 

### ISSUE THREAD

**Issue by mosonyi** [integritee-network/parachain#74]
To be able to easily monitor our validators we would need a new metric like moonbeam has: substrate_proposer_block_constructed_count 
@clangenb we already spoke about this
Thanks

**Comment by clangenb** [comment]
I have had a hard time finding out where they enable this metric. I have checked:

* Moonbeam repo itself
* Purestakes substrate fork on branch: polkadot-v0.9.17
* Purestakes cumulus fork on branch: polkadot-v0.9.17

**Comment by clangenb** [comment]
I filed an issue there: https://github.com/PureStake/moonbeam/issues/1349

**Comment by clangenb** [comment]
From the discussion in https://github.com/PureStake/moonbeam/issues/1349 I was guided to the suitable metric:

https://github.com/PureStake/substrate/blob/master/client/proposer-metrics/src/lib.rs#L69.

They seemed to have a renaming, which is probably why our metric shows 0.

**Comment by mosonyi** [comment]
As far as I understood they renamed their (add a prefix).  Original repo: https://github.com/paritytech/substrate/blob/master/client/proposer-metrics/src/lib.rs#L69
Which doesn't give an explanation why our value is always 0. I believe it shouldn't be.
Example: substrate_proposer_block_constructed_count 0

**Comment by clangenb** [comment]
Yeah, there was a renaming:

`substrate_proposer_block_constructed_count ` -> `substrate_proposer_block_constructed`

But they also added the prefix, which I don't understand the implications of.

**Comment by mosonyi** [comment]
More info: in integritee-node it is working.

**Comment by haerdib** [comment]
To document and answer the questions that came up during some offline discussion: 

**1. Is there a metric that is able to replace `substrate_proposer_block_constructed_count` that we could use instead?**
I've looked through several metrics, but I didn't find any metric that I'm 100% sure of that is capable of replacing `substrate_proposer_block_constructed_count`. 

**2. Does the `substrate_proposer_block_constructed_count` metric even work for a collator?**
Yes, it should be available for a collator according to my own understanding after looking through the cumulus code and also according to the FAQ of moonbeam:

https://docs.moonbeam.network/node-operators/networks/collators/faq/
> Q: What are the KPIs I should be monitoring?
> 
> A: The main key performance indicator is blocks produced. The prometheus metric for this is called substrate_proposer_block_constructed_count. 


So we should start looking into why our count stays a 0 even though there are blocks being produced.

**Comment by clangenb** [comment]
Sounds correct. Might make sense to start by putting logs where the metric is being set. You'd need to patch substrate for that. Apparently, you can do this quite conveniently with `cargo diener`.

https://crates.io/crates/diener/0.3.1

**Comment by clangenb** [comment]
I have been testing something else and found the following log, I guess this is the issue:

```
[Parachain] Failed to register proposer prometheus metrics: Duplicate metrics collector registration attempted
```

**Comment by clangenb** [comment]
Ah yes, this might have been the reason in my case.

**Comment by haerdib** [comment]
Just checked with @mosonyi and both Prometheus server were successfully started

**Comment by haerdib** [comment]
I checked everything, and there is no issue with the block production, nor is there one with the parameters Prometheus should be receiving. I'm now suspecting the Prometheus registry assignment of the `proposer_factory` at start up, because these are the only metrics that are not updated. 
Biggest suspect:
[`let prometheus_registry2 = prometheus_registry.map(|r| (*r).clone());`](https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/src/service.rs#L650)
even though cumulus does the same for statemint (https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/src/service.rs#L1181)..

**Comment by haerdib** [comment]
Summary of what has been found until now:
- Block production is happening fine, no problem there. This is easily verifiable by checking the info log of a parachain node: https://github.com/paritytech/substrate/blob/master/client/basic-authorship/src/basic_authorship.rs#L518-L530
- This info is reported right after the metrics update, which is always 0: https://github.com/paritytech/substrate/blob/master/client/basic-authorship/src/basic_authorship.rs#L511-L516. Conclusion: Something is wrong with the metrics report. 
- Most metrics are working. The only metrics that are not working seem to be within the `proposer_factory` (which is instantiated twice: https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/src/service.rs#L656 & https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/src/service.rs#L712)
- Sometimes (not always, though? Should double-check with @mosonyi), the following message is printed: `[Parachain] Failed to register proposer prometheus metrics: Duplicate metrics collector registration attempted`. This might be a hint.
-  Moonbeam does not experience the same issue. So we might find what we're looking for there:  https://github.com/PureStake/moonbeam/blob/490dacf6b192e51dc1bca1fbd1759c6d5fabfadf/node/service/src/lib.rs#L29. But adding a Prefix on the parachain, does not solve the issue ( tried this with https://github.com/integritee-network/parachain/tree/b18409624b222abb295ca2a0bb6ef39702776396).

What I'd try next: Do not initiate two consensus at start up (see https://github.com/integritee-network/parachain/blob/master/polkadot-parachains/src/service.rs#L221). That might cause the duplicate metrics collision.
