### ISSUE TITLE
[shell] introduce vesting for investor allocations

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#8]
It would be good to prepare vesting schedules one by one during shell phase and then go online

But we must ensure that during shell phase, nobody else than sudo can make transactions of tokens (disable most dispatchables from API?)

**Comment by clangenb** [comment]
Vesting is included, but why do you want to prevent investors from making transactions, once a part of their funds is unlocked?

**Comment by clangenb** [comment]
I think that removing apis introduces unnecessary complexity.

Doesn't the vesting pallet exactly prevent spending of tokens? We can just set block number when unlocking starts sufficiently high. Before that block number, nobody can perform any tx's except for the root account, who is the only one with unlocked funds. If we realize that we miscalculated the launch of the IntegriTEE chain, we can simply update the lock to an earlier/later value.


First, I thought we can easily remove the apis and simply call `system.setStorage`, but then we'd circumvent some internal validation logic of the vesting pallet, which I deem dangerous.

**Comment by brenzi** [comment]
This is only partially right. If we want to make a defined percentage transferrable immediately (as soon as the "full" runtime is active, we could only do that by preventing extrinsics other than sudo.
We could manually solve this be transferring the free percentage upon new runtime...a few blocks later

**Comment by brenzi** [comment]
shell now has vesting but transfers are not blocked. This means the moment when we start doing vesting transfers will be considered the TGE and the runtime upgrade has to follow immediately thereafter to give the parachain its utility
