### ISSUE TITLE
Final migration from solo- to parachain

### ISSUE THREAD

**Issue by haerdib** [integritee-network/parachain#81]
This task is the final migration from solo to the parachain. The following steps need to be executed in order:

1. Set up the necessary nodes: local solo chain and parachain node for fast state migration
2. Stop block production of the solo chain (or at least disable all calls) (runtime upgrade should have been prepared in #80 )
3. Add Pallet Migration to parachain runtime
4. Take a snapshot and run the state migration script
5. After success, re-enable normal extrinsic again
6. Re-register enclaves on the parachain
7. Communicate success (exchange, users, ...)

**Comment by mullefel** [comment]
Teeracle will be deployed directly
