### ISSUE TITLE
make srtool CI work for integritee runtime (LLVM update)

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#9]
we have a deterministic build for shell, but not for integritee runtime.

**Comment by clangenb** [comment]
This might be resolved by itself: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1530-2021-06-17

 tl;dr: rustc 1.53 has updated the minimum external LLVM version to 10. As substrate uses the nightly compiler, I reckon the srtool github action will follow soon.

**Comment by clangenb** [comment]
Requested LLVM update at srtool-actions: https://github.com/chevdor/srtool-actions/issues/2

**Comment by clangenb** [comment]
chevdor, already responded that he will look into it.

**Comment by clangenb** [comment]
srtools has updated its docker image. Simply re-enabling the integritee-runtime build in srtools led to a successful build.
