### ISSUE TITLE
test HRMP with Acala/Karura on Rococo

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#99]
In alignment with Acala team:

- [x] Update rococo runtime (https://github.com/integritee-network/parachain/commit/90eb7b476f843951e96bac54d3e5dc309b72aab8)
- [x] open an HRMP channel with Acala's rococo parachain
- [x] transfer TEER token

**Comment by haerdib** [comment]
To be finished .. 
Preparatory steps necessary to open an HRMP channel:
- [ ] Ensure the parachain account has sufficient balance (according to https://acala.discourse.group/t/open-hrmp-cross-chain-communication-between-kintsugi-and-karura-parachain/594 atleast 10 KSM..)
The parachain account address is printed in the logs at node start up.
- [ ] Ensure our parachain knows  the rococo xcmp version ( should be 2)

**Comment by haerdib** [comment]
Successfully tested on Rococo
